---
listing:
  contents: posts
  type: default
page-layout: full
---

# Ставка на информационную защиту. Возросшие риски кибератак усиливают запрос на интернет-безопасность

Российский рынок кибербезопасности переживает непростой период трансформации. Уход из РФ иностранных вендоров и поставщиков, массированные кибератаки на российские госучреждения и бизнес-структуры, фокус государства на импортозамещение, миграция и перераспределение профессиональных кадров вынуждают компании, работающие в сфере информационной безопасности (ИБ), перестраивать текущие процессы и менять повестку развития. О перспективах российского рынка ИБ в условиях обоюдоострого кризиса доверия с западными партнерами и новых подходах к защите от киберугроз.

## Контекст

Российский рынок информационной безопасности лихорадит: почти одномоментно его покинули десятки крупных иностранных игроков. За собой закрыли дверь [IBM](https://lenta.ru/tags/organizations/ibm/), [Microsoft](https://lenta.ru/tags/organizations/microsoft/), Dell, [Cisco](https://lenta.ru/tags/organizations/cisco/), [Oracle](https://lenta.ru/tags/organizations/oracle/), [Google](https://lenta.ru/tags/organizations/google/) Cloud, Fortinet, VMWare, Norton, ESET, Broadcom и другие известные мировые бренды. При этом спрос на продукты ИТ-отрасли стремительно растет. Информационная безопасность стала базовой потребностью для российского бизнеса и государства в целом.

Напомним, 1 мая 2022 года вступил в силу указ президента [Владимира Путина](https://lenta.ru/tags/persons/putin-vladimir/) «О дополнительных мерах по обеспечению информационной безопасности Российской Федерации», одним из ключевых моментов которого является введение персональной ответственности за киберинциденты для руководителей госкомпаний. Документ предписывает таким организациям с 1 января 2025 года перейти на отечественный софт.

Кроме того, госкомпаниям с 31 марта 2022 года запрещено закупать без согласования иностранное программное обеспечение для использования на таких объектах. Под действие закона, по оценкам Минцифры, подпадают сотни тысяч компаний. Новый подход к системе безопасности на государственном уровне свидетельствует о том, что рынок ИБ вступает в новую эпоху своего развития, когда формальное отношение к вопросам киберугроз себя изжило.

По оценкам экспертов, российский рынок ИБ достаточно зрел для того, чтобы компенсировать уход компаний-конкурентов и предложить отечественные продукты, не уступающие в качестве. Как следствие, в ближайшие несколько лет рынок будет показывать впечатляющие темпы роста, а на бирже можно ожидать появления новых эмитентов из продуктово-технологических ниш.

На текущий момент, напомним, торгуются лишь акции Positive Technologies --- крупного отечественного игрока на рынке кибербезопасности, который недавно объявил о выплате дивидендов на общую сумму 950 миллионов рублей, что эквивалентно 50 процентам чистой прибыли компании за 2021 год. При этом компания заявляла, что ожидаемый объем продаж в 2022 году составит 12-15 миллиардов рублей. В дальнейшем именно компании ИБ способны стать одним из локомотивов по темпам развития и продемонстрировать, что импортозамещение может декларироваться не только на бумаге.

## Точки роста

Представители отечественного рынка ИБ вошли в период пандемийных ограничений с пониманием возрастающего внимания к их разработкам. Как следствие, в 2020-2021 годах в отраслях преобладал сдержанный оптимизм, нашедший подтверждение в годовых отчетах. По данным информационно-аналитического центра Anti-malware, по итогам 2020 года совокупный объем российского рынка ИБ превысил 142 миллиарда рублей (более 2 миллиардов долларов).

В 2021-м рост рынка, по предварительным подсчетам, находился в пределах 15-17 процентов. Эти цифры формировались за счет основных направлений: защиты инфраструктуры, услуг ИБ, управления доступом, защиты приложений и защиты данных, управления ИБ. Львиная доля рынка и ранее, и в текущих условиях приходится на защиту инфраструктуры (особенно в контексте сетевой безопасности) и такие услуги как внедрение, аутсорсинг, консалтинг, оценка защищенности клиента.

В конце первого квартала 2022 года в связи с обострившейся геополитической ситуацией рынок вошел в период неопределенности с одномоментно изменившимися правилами игры, возросшими рисками, отсутствием взаимного доверия с зарубежными партнерами. Главные риски, которые в режиме нон-стоп вынуждена решать отрасль, --- возросшее в 4 раза число кибератак, уход иностранных вендоров и необходимость оперативного внедрения отечественного ПО. Тем не менее сложившаяся ситуация, господдержка ИТ-отрасли и смена приоритетов в пользу ИБ в сознании бизнеса и государства способны обеспечить отечественным компаниям новые точки роста и сделают их бенефициарами такого положения дел.

По словам директора по продажам и развитию бизнеса в России и странах СНГ Positive Technologies [Максима Филиппова](https://lenta.ru/tags/persons/filippov-maksim/), высвободившаяся после ухода иностранных вендоров из России ниша оценивается не менее, чем в 80 миллиардов рублей. «Не знаю, вырастет ли рынок, но освободившаяся ниша точно будет заполнена отечественными игроками. Главный вызов перед индустрией кибербеза заключается в том, смогут ли российские производители сделать это качественно и надежно», --- отметил эксперт.

Аналитик ФГ «Финам» [Леонид Делицын](https://lenta.ru/tags/persons/delitsyn-leonid/) также считает, что российские компании находятся в удачной позиции для замещения иностранных. «Распространение новых ИТ-решений для корпораций, таких как облачная инфраструктура, управление распределенной структурой по технологии SD WAN, у нас не успели широко распространиться, а соответственно, российские корпорации не успели плотно подсесть на западные решения. У них есть возможность просто следовать за спросом. Кроме того, современный период --- это время кибервойн, где новые способы атаки изобретаются каждый день и быстро устаревают, так что вряд ли западные компании имеют тут большое преимущество», --- отметил эксперт.

## Киберугрозы --- серьезный вызов

Чаще всего целями кибератак становятся госучреждения, промышленность, ИТ и телекоммуникационный сектор. По данным [«Лаборатории Касперского»](https://lenta.ru/tags/organizations/laboratoriya-kasperskogo/), в 2021 году по сравнению с предыдущим годом доля инцидентов высокой степени критичности, то есть оказывающих значительное влияние на бизнес, выросла с 9 до 14 процентов, а количество кибератак увеличилось на 6,5 процента год к году. Так, в [Сбербанке](https://lenta.ru/tags/organizations/sberbank-rossii/) заявляли, что ежедневно специалистам банка приходится отражать несколько десятков DDoS-атак. Число хакеров, покушающихся на кибербезопасность банка, превышает 100 тысяч человек. В последние несколько месяцев ситуация только усугубилась.

В новых условиях было принято решение запретить госорганам использовать иностранное программное обеспечение на объектах критической информационной инфраструктуры. По мнению экспертов, соответствующий указ президента Владимира Путина создает благоприятные условия для отечественных компаний, способных предложить свои решения для ИБ. Растущий спрос на решения и услуги в области кибербезопасности будет наблюдаться со стороны банковского, финансового, ИТ, телекоммуникационного секторов, а также госучреждений и предприятий малого и среднего бизнеса.

Конкурентные аналоги отечественного производства не стоит недооценивать: их давно и успешно применяют в самых различных областях. На вопрос, реально ли собственными силами защитить отечественный бизнес и госструктуры от кибератак, эксперты отвечают утвердительно. Так, в Positive Technologies прогнозируют, что определяющим для рынка будет переход на метапродукты, первый из которых --- MaxPatrol O2 --- обнаруживает хакера в автоматическом режиме до того, как он сумеет нанести непоправимый ущерб. При этом результат достигается силами одного человека.

Киберучения и соревнования среди ИБ-специалистов и «белых» хакеров также признаны эффективным инструментом для построения надежной информационной защиты. На международном форуме по практической безопасности Positive Hack Days министр цифрового развития, связи и массовых коммуникаций Российской Федерации [Максут Шадаев](https://lenta.ru/tags/persons/shadaev-maksut/) подчеркнул, что «постоянный поиск уязвимостей специализированными командами --- правильная практика, которая должна стать гигиеническим минимумом при построении информационной безопасности в любой компании».

Таким образом, воздействие внешних факторов, формирующих новую реальность, заставляет ИБ-сектор перераспределять ресурсы, быстрее адаптироваться к потребностям клиентов, создавать новые продукты и интенсивно расти.
